In [1]:
using LinearAlgebra

In [ ]:
A = ones(1)

In [ ]:
b = vcat(A, [2])

In [7]:
include("terms_and_polynomials.jl");

In [10]:
a = SetsOandG(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)

SetsOandG(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)

In [ ]:
hcat(1, 1)

In [11]:
update_O(a, 2, 2, 2)

1×2 Matrix{Int64}:
 1  2

In [12]:
a.O_terms

1×2 Matrix{Int64}:
 1  2

In [13]:
b = ones(1, 1)

1×1 Matrix{Float64}:
 1.0

In [15]:
b .+ 2

1×1 Matrix{Float64}:
 3.0